### ISSUE TITLE
Derive Clone for ZipfDistribution?

### ISSUE THREAD

**Issue by kennytm** [jonhoo/rust-zipf#3]
Currently [`ZipfDistribution` does not implement `Clone`](https://docs.rs/zipf/4.0.0/zipf/struct.ZipfDistribution.html#implementations), but it should be very easy to derive it. 

For comparison, the distributions in `rand` e.g. [`LogNormal`](https://docs.rs/rand/0.5.5/src/rand/distributions/normal.rs.html#135) derived `Copy + Clone + Debug`.

**Comment by jonhoo** [comment]
Good catch! Fixed in `4.0.1`.
